### ISSUE TITLE
Error on array of link objects

### ISSUE THREAD

**Issue by basti1302** [xcambar/halbert#5]
The spec says:

> 4.1.1.  _links
> 
> The reserved "_links" property is OPTIONAL.
> 
> It is an object whose property names are link relation types (as defined by [RFC5988]) and values are either a Link Object **or an array of Link Objects**.  The subject resource of these links is the Resource Object of which the containing "_links" object is a property.

Thus, this is valid HAL:

```
{
  "_links": {
    "self": { "href": "/orders" },
    "admin": [                                                                   
       { "href": "/admins/2", "title": "Fred" },
       { "href": "/admins/5", "title": "Kate" }
    ]
  }
}
```

Halbert currently can not parse this:

```
TypeError: Invalid parameter passed to Link constructor
  at new Link (/home/bastian/projekte/halbert/src/link.js:16:11)
  at /home/bastian/projekte/halbert/src/links.js:19:16
  at Array.forEach (native)
  at new Links (/home/bastian/projekte/halbert/src/links.js:18:21)
  at new Resource (/home/bastian/projekte/halbert/src/resource.js:23:23)
  at parser (/home/bastian/projekte/halbert/src/parser.js:15:10)
```

The reason is that the array is passed to `utils.isObjectLiteral` which checks the type and only accepts object.

While this is easy to fix, I'm not sure how Halbert should make the array of links available to the client (the code using Halbert) in a convenient fashion. The straightforward way would be like this, I suppose

```
it("should parse the an array of links", function () {                  
  ...
  var resource = parser(json);                                               
  resource.links('admin')[0].href.should.equal('/admin/2');                  
  resource.links('admin')[1].href.should.equal('/admin/5');                  
});
```

However, that puts the burden on the client to know in advance if a link relation contains an array or only a single link.

Xavier, what do you think?

Cheers,

  Bastian

**Comment by xcambar** [comment]
If it's an object, I would expose it as a an array with a single element.

After readng the spec again, it doesn't seem to make any semantic difference.

**Comment by basti1302** [comment]
Array with a single element would work. Downside is, it pollutes the clients code with links('rel')**[0]** for the 80 - 90% case where it's not an array. But currently I do not have a more elegant idea.
